# Generated by Django 3.2.4 on 2021-10-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='width',
            field=models.FloatField(null=True),
        ),
    ]
