"""
Django settings for this project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from core.settings.base import *
from core.settings.base_w_gcloud import *
from sentry_sdk.integrations.django import DjangoIntegration
# from firebase_admin import credentials, initialize_app
import sentry_sdk
import newrelic.agent

ALLOWED_HOSTS = ['localhost']

# Setup Firebase for notification
# FIREBASE_CREDENTIALS = json.loads(os.environ.get('FIREBASE_CREDENTIALS', '{}'))
# initialize_app(credentials.Certificate(FIREBASE_CREDENTIALS))

# redis cache setup
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'temp'),
    },
    'redis': {
        'BACKEND': 'redis_cache.cache.RedisCache',
        'LOCATION': f'{REDIS_HOST}:{REDIS_PORT}',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'MAX_ENTRIES': 5000,
        },
    },
}

# New Relic
newrelic.agent.initialize(os.path.join(BASE_DIR, 'newrelic.ini'))


# Sentry
sentry_sdk.init(
    dsn="your-project-name-sentry-sdn",
    integrations=[DjangoIntegration()],

    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    traces_sample_rate=1.0,

    # If you wish to associate users to errors (assuming you are using
    # django.contrib.auth) you may enable sending PII data.
    send_default_pii=True
)

